package pt.agap2.academy.huddleup.daos;

import java.util.Date;

import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import pt.agap2.academy.huddleup.configs.TestConfiguration;
import pt.agap2.academy.huddleup.daos.dtos.EventDetails;
import pt.agap2.academy.huddleup.model.HuddleEvent;
import pt.agap2.academy.huddleup.model.Location;
import pt.agap2.academy.huddleup.model.User;

@RunWith(SpringJUnit4ClassRunner.class )
@ContextConfiguration( classes= TestConfiguration.class)
public class HuddleEventDAOTest {

	
	@Autowired
	private HuddleEventDAO huddleEventDao;
	
	@Autowired
	private UserDAO userDao;
	
	public static HuddleEvent getDemoHuddleEvent(User existentUser){
		
		HuddleEvent event = new HuddleEvent();
		event.setAddress("Rua  das Pretas");
		event.setCity("Porto");
		event.setDescription("Great Event");
		event.setEventDate(new  Date());
		event.setEventName("Mega party");
		event.setEventType("Party");
		event.setHost( existentUser );
		event.setIsDeleted(false);
		event.setLocation( new Location(34.0f,35.4f) );
		event.setMaxAtt(10);
		event.setPhoto(null);
		event.setRequirements("Drinks");
		
		return event;
	}
	
	@Test
	public void springIsWorking(){
		
		Assert.assertNotNull(this.huddleEventDao);
	}
	
	@Test
	public void insertEvent(){
		
		User  user = UserDAOTest.getDemoUser();
		this.userDao.save(user);
		
		HuddleEvent event = getDemoHuddleEvent(user);
		
		this.huddleEventDao.save(event);
		
		// test if the  event was inserted
		Assert.assertNotNull( this.huddleEventDao.findOne(event.getId()) );
	}
	
	
	@Test
	public void testAutogeneratedMethod(){
		
		User  user = UserDAOTest.getDemoUser();
		this.userDao.save(user);
		HuddleEvent event = getDemoHuddleEvent(user);
		event.setCity( "abrantes" );
		this.huddleEventDao.save(event);
		
		
		EventDetails eventDetails = this.huddleEventDao.findEventDetailsById(event.getId()); 
		Assert.assertTrue( eventDetails.getCity().equals("abrantes") );
		
	}
	
}
